config/routes.rb
Rails.application.routes.draw do
  get 'games/new'
  get 'games/score'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  Rails.application.routes.draw do
    get '/new', to: 'games#new'
    post '/score', to: 'games#score'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController
  def new
    @letters = Array.new(10) { ('A'..'Z').to_a.sample }
  end

  def score
    @word = params[:word]
    @letters = params[:letters].split(' ')
    @result = {}

    if included?(@word.upcase, @letters)
      if english_word?(@word)
        @result[:score] = @word.length
        @result[:message] = "Congratulations! #{@word} is a valid English word!"
      else
        @result[:score] = 0
        @result[:message] = "Sorry but #{@word} does not seem to be a valid English word..."
      end
    else
      @result[:score] = 0
      @result[:message] = "Sorry, but #{@word} can't be built out of #{@letters}."
    end

    respond_to do |format|
      format.json { render json: @result }
    end
  end

  def included?(word, letters)
    word.chars.all? { |letter| word.count(letter) <= letters.count(letter) }
  end

  def english_word?
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    return json['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New game</h1>

<ul>
  <% @letters.each do |letter| %>
    <li><%= letter %></li>
  <% end %>
</ul>

<%= form_tag(score_path, method: :post, data: { turbo: false }) do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <p>
    <%= label_tag(:word, "Enter a word:") %>
    <%= text_field_tag(:word) %>
  </p>
  <%= submit_tag("Submit") %>
<% end %>

app/views/games/score.html.erb
<h1>Games#score</h1>
<p>Find me in app/views/games/score.html.erb</p>

<%= link_to "Play Again", new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>